export const AVAILABLE_VEHICLES_IDS = ['1234', '1235']
export const VEHICLE_COMMANDS = ['START_VEHICLE', 'STOP_VEHICLE']
export const VEHICLE_COMMANDS_OBJECT = {
  START_VEHICLE: 'START_VEHICLE',
  STOP_VEHICLE: 'STOP_VEHICLE',
}
export const VEHICLE_ACTIONS = ['START', 'STOP']
export const VEHICLE_ACTIONS_OBJECT = {
  START: 'START',
  STOP: 'STOP',
}